from __future__ import absolute_import

import os
import numpy as np

# Assume CASA 6, CASA 5 is no longer built
from casatools import image
ia = image()


class ImagingDict():
    """
    Class that constructs the tclean return dictionary - implemented
    specifically for the niter=0 case, to reproduce the dictionary generated in
    C++ without modifying the C++ code.

    Attributes:
    -----------
    residname       : Name of the input residual image (required)
    modelname       : Name of the input model image (optional)
    summaryminor    : The dictionary containing summaryminor
    retrec          : The full return dictionary

    Methods:
    --------

    imageDimensions(residname)
        Use the image() tool to query for the number of Stokes planes and
        frequency channels in the input image.

    fillSummaryMinor(residname, modelname, channo, stokes, stokes_axis, freq_axis, fullsummary):
        Given the input image name, and the corresponding field, channel number, and
        Stokes plane, extract the relevant information from the image to generate a
        summaryminor dict as defined

    constructSummaryMinor(self, paramList):
        Constructs and populates a nested dictionary containing the summaryMinor()
        information required by tclean.
        This is a duplicate of the existing summaryMinor() class in C++, but is
        being re-written here to avoid issues with modifying iterControl.

    constructResidualDict(paramList):
        Construct the residual dictionary given the input image name and associated parameters. This residual dictionary is meant to
        duplicate that generated by imager.getSummary(fullsummary) for the special
    """

    def __init__(self) -> None:
        self._returndict = {}
        self._summaryminor = {}

        # These three parameters cannot be assigned, only accessed.
        # They reflect the values in the summaryminor key in the return dict.

        self._nfield = 0
        self._nstokes = 0
        self._nchan = 0

        self.residname = ''
        self.modelname = ''

        self._initialize()

        self._summaryminor_keys = ['iterDone', 'peakRes', 'modelFlux', 'cycleThresh',
                                   'cycleStartIters', 'startIterDone',
                                   'startPeakRes', 'startModelFlux',
                                   'startPeakResNM', 'peakResNM', 'masksum',
                                   'mpiServer', 'stopCode']

    def __str__(self) -> str:
        """
        Pretty print the return dictionary.
        """

        retstr = ''
        for key, val in self._returndict.items():
            if key == 'summaryminor':
                retstr += 'summaryminor:\n'
                for field in val.keys():
                    for freq in val[field].keys():
                        for stokes in val[field][freq].keys():
                            for key2, val2 in val[field][freq][stokes].items():
                                retstr += f'\t Field: {field: 3d}, Chan: {freq: 3d}, Stokes: {stokes :2d}, {key2}, {val2}\n'
            else:
                retstr += f'{key}: {val}\n'
        return retstr

    @property
    def returndict(self) -> dict:
        return self._returndict

    @returndict.setter
    def returndict(self, inpdict: dict) -> None:
        self._returndict = inpdict

    @returndict.deleter
    def returndict(self) -> None:
        del self._returndict

    @property
    def nfield(self) -> int:
        self._nfield = len(self._returndict['summaryminor'].keys())
        return self._nfield

    @nfield.deleter
    def nfield(self) -> None:
        del self._nfield

    # XXX : This assumes that the number of channels is the same for all fields
    @property
    def nchan(self) -> int:
        self._nchan = 0
        for field in self._returndict['summaryminor'].keys():
            self._nchan = len(self._returndict['summaryminor'][field].keys())
            break

        return self._nchan

    @nchan.deleter
    def nchan(self) -> None:
        del self._nchan

    @property
    def nstokes(self) -> int:
        self._nstokes = 0
        for field in self._returndict['summaryminor'].keys():
            for freq in self._returndict['summaryminor'][field].keys():
                self._nstokes = len(self._returndict['summaryminor'][field][freq].keys())
                break

        return self._nstokes

    @nstokes.deleter
    def nstokes(self) -> None:
        del self._nstokes

    def _initialize(self) -> None:
        """
        Initialize the return dictionary with dummy values. This sets up the
        dictionary structure and keys to expect, and will be filled in with
        real values when running tclean or deconvolve.
        """

        # Initialize the values that don't need to inspect any images
        self._returndict['cleanstate'] = ''
        self._returndict['cyclefactor'] = 1.0
        self._returndict['cycleiterdone'] = 0
        self._returndict['cycleniter'] = 0
        self._returndict['cyclethreshold'] = 0
        self._returndict['interactiveiterdone'] = 0
        self._returndict['interactivemode'] = False
        self._returndict['interactiveniter'] = 0
        self._returndict['interactivethreshold'] = 0

        self._returndict['iterdone'] = 0
        self._returndict['loopgain'] = 0
        self._returndict['maxpsffraction'] = 0
        self._returndict['maxpsfsidelobe'] = 0
        self._returndict['minpsffraction'] = 0

        self._returndict['niter'] = 0
        self._returndict['nmajordone'] = 0
        self._returndict['nsigma'] = 0.0
        self._returndict['stopcode'] = 0

        self._returndict['summarymajor'] = np.array([])
        # Summary minor is nested as {field{freq{stokes}}
        # TODO : Figure out a better way to initialize the empty summary minor
        # without explicitly setting a field/stokes/channel number.
        self._returndict['summaryminor'] = {}
        self._returndict['summaryminor'][0] = {}
        self._returndict['summaryminor'][0][0] = {}
        self._returndict['summaryminor'][0][0][0] = self._initialize_summary_minor()

        self._returndict['threshold'] = 0.0
        self._returndict['stopDescription'] = 'Zero iterations performed'


    def _initialize_summary_minor(self) -> dict:
        """
        Initialize the summary minor dictionary with dummy values. This sets up the
        dictionary structure and keys to expect, and will be filled in with
        real values when running tclean or deconvolve.
        """

        self._summaryminor['iterDone'] = []
        self._summaryminor['peakRes'] = []
        self._summaryminor['modelFlux'] = []
        self._summaryminor['cycleThresh'] = []
        self._summaryminor['cycleStartIters'] = []
        self._summaryminor['startIterDone'] = []
        self._summaryminor['startPeakRes'] = []
        self._summaryminor['startModelFlux'] = []
        self._summaryminor['startPeakResNM'] = []
        self._summaryminor['peakResNM'] = []
        self._summaryminor['masksum'] = []
        self._summaryminor['mpiServer'] = []
        self._summaryminor['stopCode'] = []

        return self._summaryminor



    def get_key(self, key:str, field:int=0, chan:int=0, stokes:int=0) -> list:
        """
        Return the list of values for the specified key. If requesting a key
        within "summaryminor", also specify the field, channel and stokes plane.

        Inputs:
        key         The key to return. str
        field       The field to return. int
        chan        The channel to return. int
        stokes      The stokes plane to return. int

        Returns:
        The list of values for the specified key. list
        """

        try:
            if key in self._summaryminor_keys:
                return self._returndict['summaryminor'][field][chan][stokes][key]
            else:
                return self._returndict[key]
        except KeyError:
            print(f'WARNING : Key {key} not found in return dictionary.')
            return []



    #def get_summaryminor_key_allplanes(self, key:str) -> dict:
    #    """

    #    Return a structured dictionary over all channels & stokes in the returndict.
    #    This returns a dictionary in the form :

    #    keydict[nstokes][nchan]['keyname'] = [....]

    #    If the key does not exist within 'summaryminor' and exception will be thrown.

    #    Inputs:
    #    key         The key to return. str

    #    Returns:
    #    keydict     Dictionary that contains the key value for every stokes/chan plane
    #    """

    #    if key not in self._summaryminorkeys:
    #        raise KeyError(
    #            f"Input key {key} not in summaryminor. Please use one of {self._summaryminorkeys}")

    #    keydict = {}

    #    smdict = self._returndict['summaryminor']

    #    for field in smdict:
    #        keydict[field] = {}
    #        for chan in smdict[field]:
    #            keydict[field][chan] = {}
    #            for stokes in smdict[field][chan]:
    #                keydict[field][chan][stokes] = self.get_key

    def merge(self, dict1: dict, dict2: dict, key_path=[]) -> None:
        """
        Merge the two input dictionaries, and return the merged dictionary.

        The merge recurses into the dictionary, and obeys the following rules:
        1. If the key exists in both dictionaries, merge the values
            a. If the value is numeric, add the values
            b. If the value is a string, use the value from dict2
        2. If the key exists in only one dictionary, copy the value
        3. If the key is a dictionary, recurse into the dictionary

        The input dictionary must be a fully formed return dictionary from
        either `tclean` or `deconvolve`.

        Inputs:
        dict1     The input dictionary to merge. dict
        dict2     The input dictionary to merge. dict
        key_path  The path to the current key. Used for recursion. list

        Returns:
        merge_dict
        """

        # Taken from SO :
        # https://stackoverflow.com/questions/7204805/deep-merge-dictionaries-of-dictionaries-in-python/7205107#7205107

        for key, val in dict2.items():
            if key in dict1:
                if isinstance(dict1[key], dict) and isinstance(dict2[key], dict):
                    dict1[key] = self.merge(dict1[key], dict2[key], key_path + [str(key)])
                elif dict1[key] == dict2[key]:
                    if isinstance(val, (int, float, complex)):
                        dict1[key] += val
                    if isinstance(val, str):
                        dict1[key] = val
            else:
                dict1[key] = val

        return dict1


    def concat(self, dict1:dict, dict2:dict) -> None:
        """
        Concatenate the two input dictionaries. The input dictionary must be a
        fully formed return dictionary from either `tclean` or `deconvolve`.

        The append recurses into the dictionary, and obeys the following rules:
        1. If the key exists in both dictionaries, concatenate the values
            a. If the value is numeric or a list, concatenate the values
            b. If the value is a string, use the value from dict2
        2. If the key exists in only one dictionary, copy the value
        3. If the key is a dictionary, recurse into the dictionary

        Inputs:
        dict1     The input dictionary to append. dict
        dict2     The input dictionary to append. dict

        Returns:
        appendix  The concatenated dictionary. dict
        """

        appendix = {}

        # All unique keys
        dict_keys = list(dict1.keys()) + [key for key in dict2.keys() if key not in dict1.keys()]
        print("dict_keys are ", dict_keys)

        for key in dict_keys:
            if isinstance(dict1[key], dict) and isinstance(dict2[key], dict):
                appendix[key] = self.concat(dict1[key], dict2[key])
            elif isinstance(dict1[key], list) and isinstance(dict2[key], list):
                appendix[key] = dict1[key] + dict2[key]
            elif isinstance(dict1[key], np.ndarray) and isinstance(dict2[key], np.ndarray):
                # Using a list allows either key to be completely empty
                # numpy.concatenate breaks if one or both are length 0
                temparr = []
                temparr.extend(dict1[key])
                temparr.extend(dict2[key])
                appendix[key] = np.array(temparr)
            elif isinstance(dict1[key], (int, float, complex)) and isinstance(dict2[key], (int, float, complex)):
                # TODO : Clean up the numeric tuple after the move to Python 3.10
                appendix[key] = dict1[key] + dict2[key]
            elif isinstance(dict1[key], str) and isinstance(dict2[key], str):
                appendix[key] = dict2[key]
            else:
                # This should never happen for a well behaved tclean dict.
                raise TypeError(f'Cannot append {key} of type {type(dict1[key])} and {type(dict2[key])}')

        return appendix



    def imageDimensions(self):
        """
        Given the input image, uses the ia tool to query for the number of Stokes
        planes and frequency channels.

        Inputs:
        None

        Returns:
        nstokes         Number of Stokes planes in the image
        nfreq           Number of frequency channels in the image
        """
        ia = image()

        # At this point we've already checked residname exists
        ia.open(self.residname)
        csys = ia.coordsys()

        shape = ia.shape()

        #  Figure out which axis is which
        stokes_axis = csys.findaxisbyname('Stokes')
        freq_axis = csys.findaxisbyname('Frequency')

        nstokes = shape[stokes_axis]
        nfreq = shape[freq_axis]

        ia.close()

        return nstokes, nfreq, stokes_axis, freq_axis


    def fillSummaryMinor(self, channo, stokes, stokes_axis, freq_axis, fullsummary):
        """
        Given the input image name, and the corresponding field, channel number, and
        Stokes plane, extract the relevant information from the image to generate a
        summaryminor dict as defined
        https://casadocs.readthedocs.io/en/stable/notebooks/synthesis_imaging.html#Minor-Cycle-Summary-Dictionary

        Inputs:
        channo          Channel number to query in the image, int
        stokes          Stokes plane to query in the image, int
        stokes_axis     The axis to index for Stokes, int
        freq_axis       The axis to index for frequency, int
        fullsummary     Construct a full summary, or only a subset, bool

        Returns:
        summaryparams     Dict containing the necessary (key:value) pairs
        """

        ia = image()

        if not os.path.exists(self.residname):
            raise FileNotFoundError(f'Residual image {self.residname} does not exist.')

        ia.open(self.residname)
        shape = ia.shape()

        if stokes_axis == 2 and freq_axis == 3:
            blc = [0, 0, stokes, channo]
            trc = [shape[0], shape[1], stokes, channo]
        elif stokes_axis == 3 and freq_axis == 2:
            blc = [0, 0, channo, stokes]
            trc = [shape[0], shape[1], channo, stokes]

        data = ia.getchunk(blc, trc, dropdeg=True)
        mask = ia.getchunk(blc, trc, dropdeg=True, getmask=True)
        ia.close()

        # If model image exists, calc model flux, else set to 0
        model_sum = 0
        if os.path.exists(self.modelname):
            ia.open(self.modelname)
            model_data = ia.getchunk(blc, trc, dropdeg=True)
            model_sum = np.sum(model_data)
            ia.close()

        peak_resid = np.amax(data*mask)
        if fullsummary:
            peak_resid_NM = np.amax(data)
            mask_sum = np.sum(mask)

        summaryparams = dict()
        # This entire function is only invoked in the special case of niter=0
        summaryparams['iterDone'] = [0.0,]
        summaryparams['peakRes'] = [peak_resid,]
        # model flux has to be zero because no iterations were performed
        summaryparams['modelFlux'] = [model_sum,]
        # No threshold because no deconvolution done
        summaryparams['cycleThresh'] = [0.0,]

        if fullsummary:
            summaryparams['cycleStartIters'] = [0.0,]
            summaryparams['startIterDone'] = [0.0,]
            summaryparams['startPeakRes'] = [peak_resid,]
            summaryparams['startModelFlux'] = [model_sum,]
            summaryparams['startPeakResNM'] = [peak_resid_NM,]
            summaryparams['peakResNM'] = [peak_resid_NM,]
            summaryparams['masksum'] = [mask_sum,]
            summaryparams['mpiServer'] = [0.0,]
            summaryparams['stopCode'] = [3,]


        return summaryparams


    def constructSummaryMinor(self, paramList):
        """
        Constructs and populates a nested dictionary containing the summaryMinor()
        information required by tclean.

        This is a duplicate of the existing summaryMinor() class in C++, but is
        being re-written here to avoid issues with modifying iterControl.

        Inputs:
        paramList        Object that contains all imaging parameters

        Returns:
        None
        """

        impars = paramList.allimpars
        decpars = paramList.alldecpars

        # Each field is stored as a different key in impars
        nfields = len(impars.keys())

        for ff in range(nfields):
            self.residname=impars[str(ff)]['imagename']+'.residual.tt0' if(os.path.exists(impars[str(ff)]['imagename']+'.residual.tt0')) else impars[str(ff)]['imagename']+'.residual'
            self.modelname=impars[str(ff)]['imagename']+'.model.tt0' if(os.path.exists(impars[str(ff)]['imagename']+'.model.tt0')) else impars[str(ff)]['imagename']+'.model'

            fullsummary = decpars[str(ff)]['fullsummary']
            nstokes, nfreq, stokes_axis, freq_axis = self.imageDimensions()

            if ff not in self._returndict['summaryminor']:
                self._returndict['summaryminor'][ff] = dict()

            for cc in range(nfreq):
                if cc not in self._returndict['summaryminor'][ff]:
                    self._returndict['summaryminor'][ff][cc] = dict()

                for ss in range(nstokes):
                    if ss not in self._returndict['summaryminor'][ff][cc]:
                        self._returndict['summaryminor'][ff][cc][ss] = dict()

                    self._returndict['summaryminor'][ff][cc][ss] = self.fillSummaryMinor(cc, ss, stokes_axis, freq_axis, fullsummary)




    def constructResidualDict(self, paramList):
        """
        Construct the residual dictionary given the input image name and associated parameters. This residual dictionary is meant to
        duplicate that generated by imager.getSummary(fullsummary) for the special
        case of niter = 0 to avoid initializing the deconvolver.

        Inputs:
        paramList   The tclean inputs, defaults where not specified. dict

        Returns:
        returndict  The return dictionary with imaging statistics. dict
        """

        imagename = paramList.allimpars['0']['imagename']

        self.residname = imagename+'.residual.tt0' if(os.path.exists(imagename +'.residual.tt0')) else imagename +'.residual'
        do_summary_minor = True
        # Only fill summaryminor if the residual image exists
        if not os.path.exists(self.residname):
            do_summary_minor = False
            #raise FileNotFoundError(f'{residname} does not exist on disk. Cannot construct tclean return dictionary.')

        # Initialize the values that don't need to inspect any images
        self._returndict['cleanstate'] = 'running'
        self._returndict['cyclefactor'] = paramList.getAllPars()['cyclefactor']
        self._returndict['cycleiterdone'] = 0
        self._returndict['cycleniter'] = 0
        self._returndict['cyclethreshold'] = 0
        self._returndict['interactiveiterdone'] = 0
        self._returndict['interactivemode'] = paramList.alldecpars['0']['interactive']
        self._returndict['interactiveniter'] = 0
        self._returndict['interactivethreshold'] = 0

        self._returndict['iterdone'] = 0
        self._returndict['loopgain'] = 0
        self._returndict['maxpsffraction'] = 0
        self._returndict['maxpsfsidelobe'] = 0
        self._returndict['minpsffraction'] = 0

        self._returndict['niter'] = 0
        self._returndict['nmajordone'] = 1
        self._returndict['nsigma'] = 0.0
        # stopcode 3 --> Zero iterations performed
        self._returndict['stopcode'] = 3

        self._returndict['summarymajor'] = np.array([0,])

        if do_summary_minor:
            self.constructSummaryMinor(paramList)

        self._returndict['threshold'] = 0.0
        self._returndict['stopDescription'] = 'Zero iterations performed'


        return self._returndict
