[metadata]
name = casatools
author = CASA development team
author_email = casa-feedback@nrao.edu
url = https://open-bitbucket.nrao.edu/projects/CASA/repos/casa6/browse
license = GPLv2
license_files = LICENSE.txt
description = Astronomy data reduction library
classifiers =
    Programming Language :: C
    Programming Language :: C++
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: Implementation :: CPython
    Development Status :: 5 - Production/Stable
    Environment :: Console
    Intended Audience :: Science/Research
    Intended Audience :: Developers
    License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)
    Operating System :: POSIX
    Topic :: Scientific/Engineering :: Astronomy
    Topic :: Software Development :: Libraries :: Application Frameworks
long_description = file:README.md
long_description_content_type = text/markdown

[options]
python_requires = >=3.6
packages =
    casatools
    casatools.__cerberus__
package_dir =
    casatools = src/casatools
    casatools.__cerberus__ = src/casa_cerberus
install_requires =
    numpy
    casaconfig

[options.packages.find]
where = src
exclude =
    code
