from casatools import componentlist, measures
from casatasks import casalog
from datetime import datetime, timedelta
import json
from urllib import request
from urllib.error import URLError, HTTPError
from urllib.parse import urlparse, quote


def __is_valid_url_host(url):
    parsed = urlparse(url)
    return bool(parsed.netloc)


def __query(url):
    req = request.Request(url)
    with request.urlopen(req) as response:
        if response.status != 200:
            return None
        components = json.loads(response.read().decode('utf-8'))
    return components


def __current_mjd():
    # generated by ChatGPT-4
    epoch = datetime(1858, 11, 17)  # Modified Julian Date epoch
    today = datetime.utcnow()
    days_since_epoch = (today - epoch).total_seconds() / 86400
    return int(days_since_epoch)


def calmod(
    outfile, source, direction, band, obsdate, refdate, hosts
):
    if not outfile.strip():
        raise ValueError('outfile must be specified')
    if not (source.strip() or direction.strip()):
        raise ValueError('Exactly one of source or direction must be specified')
    if source and direction:
        raise ValueError('Both source and direction may not be simultaneously specified')
    if source and source.upper() not in ("3C48", "3C286", "3C138", "3C147"):
        raise ValueError(f'Unsupported calibrator {source}')
    if direction:
        dirstr = direction.split(' ')
        if not (len(dirstr) == 3 and measures().direction(dirstr[0], dirstr[1], dirstr[2])):
            raise ValueError(f'Illegal direction specification {direction}')
    src_or_dir = source if source else direction
    if not band:
        raise ValueError('band must be specified')
    if band.upper() not in ["P", "L", "S", "C", "X", "U", "K", "A", "Q"]:
        raise ValueError(f'band {band} not supported')
    if obsdate < 44239:
        raise ValueError('obsdate must be <= 0 or >= 44239')
    if refdate > 0 and refdate < 44239:
        raise ValueError('refdate must be <= 0 or >= 44239')
    if not hosts:
        raise ValueError('hosts must be specified')
    wsid = 'type=setjy'
    wsid += f'&source={quote(source)}' if source else f'&position={quote(direction)}'
    wsid += f'&band={quote(band)}'
    wsid += f'&obsdate={int(obsdate)}'
    if refdate > 0:
        wsid += f'&refdate={int(refdate)}'
    components = None
    for h in hosts:
        if not __is_valid_url_host(h):
            raise ValueError(f'{h} is not a valid host expressed as a URL')
        url = f'{h}?{wsid}'
        casalog.post(f'Trying {url} ...', 'NORMAL')
        try:
            components = __query(url)
        except HTTPError as e:
            casalog.post(f'Caught HTTPError: {str(e)}', 'WARN')
        except URLError as e:
            casalog.post(f'Caught URLError: {str(e)}', 'WARN')
        except Exception as e:
            casalog.post(f'Caught Exception when trying to connect: {str(e)}', 'WARN')
        if components:
            break
    if not components:
        raise RuntimeError('All URLs failed to return a component list')
    cl = componentlist()
    cl.fromrecord(components)
    cl.rename(outfile)
    web_service = {}
    if source:
        web_service['source'] = source
    if direction:
        web_service['direction'] = direction
    if obsdate:
        web_service['obsdate'] = obsdate
    if refdate:
        web_service['refdate'] = refdate
    web_service['band'] = band
    web_service['hosts'] = hosts
    web_service['run_mjd'] = __current_mjd()
    web_service['url'] = url
    web_service['response'] = components
    cl.putkeyword('web_service', web_service)
    casalog.post(f'component list {outfile} has been written', 'NORMAL')
    cl.done()
    
