from casatools import componentlist, measures, quanta
from casatasks import casalog
from datetime import datetime, timedelta
import json
import numbers
import re
from urllib import request
from urllib.error import URLError, HTTPError
from urllib.parse import urlparse, quote


def __is_valid_url_host(url):
    parsed = urlparse(url)
    return bool(parsed.netloc)


def __query(url):
    req = request.Request(url)
    with request.urlopen(req) as response:
        if response.status != 200:
            return None
        components = json.loads(response.read().decode('utf-8'))
    return components

"""
def __current_mjd():
    # generated by ChatGPT-4
    epoch = datetime(1858, 11, 17)  # Modified Julian Date epoch
    today = datetime.utcnow()
    days_since_epoch = (today - epoch).total_seconds() / 86400
    return int(days_since_epoch)
"""

def calmod(
    outfile, source, direction, band, obsdate, refdate, hosts
):
    r"""
Retrieve calibrator brightness distributions from telescope-specific web services.

[`Description`_] [`Examples`_] [`Development`_] [`Details`_]


Parameters
   - outfile_ (path='') - The name of the output component list to be written. Must be specified
   - source_ (string='') - The calibrator name.
   - direction_ (string='') - The direction of the calibrator
   - band_ (string='') - The receiver band for which the source structure is needed
   - obsdate_ (variant='0') - The observation date
   - refdate_ (variant='0') - The reference date after which new database entries will be ignored.
   - hosts_ (stringVec=['http://something.nrao.edu']) - List of hostnames to use when querying the web service.


.. _Description:

Description

  This task retrieves calibrator information via telescope-specific web services
  and writes this information as a component list so that it may be used by applications
  downstream.

  The task currently supports only the VLA (since it is the only telescope that has
  such a web service). One of either a calibrator name or direction may be specified.
  The names '3C48', '3C138', '3C147', and '3C286' are supported. A direction is specified
  as 'FRAME LONGITUDE LATITUDE', so for example 'J2000 01:37:41.1 33.09.32' for 3C48. 
  Latitude and longitude may be specified in their familiar sexigesimal forms, or as
  angular quantities which must include units (eg '33.15deg'). If a direction is specified,
  the web service will attempt to find a supported calibrator near that position. If one
  cannot be found, an exception will be thrown.

  The observing band must be specified. For the VLA, supported bands are 'P'. 'L', 'S',
  'C', 'X', 'U', 'K', 'A', and 'Q'.

  The observation date must be specified as either an MJD (assumed if the value is a number)
  or a date of the form 'YYYY-MM-DD' (assumed if the value is specified as a string).
  Specifying a time before or around 1980 will result in an exception being thrown as there
  are no data for such dates.

  A reference date may be specified. If so, the specification rules for the observation
  date also hold for this parameter, Specifying this parameter allows older versions of the data
  and/or algorithms should be retrieved, thus allowing historical reproducibility even
  after data and algorithms may have been updated. This input represents the latest date
  for which versioned data and algorithms should be used.

  If successful, the task will write a component list generated from the data returned
  by the web service which represents the brightness distribution for the specified 
  calibrator for the specified band at the specified date (with the reference date applied
  if one is specified). This component list, being a CASA table, will have the table
  keyword 'web_service'. The value of this keyword is a dictionary containing the inputs
  specified in the task, the response of the web service (usually a very long JSON string),
  the URL that was used to make the query, and other possibly useful metadata.  


.. _Examples:

Examples
   
    ::

       # get the intensity distribution of 3C48 at Q band on MJD 55000
       calmode(
           outfile='3C48.cl', source='3C48', band='Q', obsdate=55000,
           hosts=['http://some-host-that-works.nrao.edu']
       )   

       # the same thing, but do not use any data or algorithms that were
       # created after MJD 56000
       calmode(
           outfile='3C48.cl', source='3C48', band='Q', obsdate=55000,
           refdate=56000, hosts=['http://some-host-that-works.nrao.edu']
       )   

       # get the same information as the first query based on 3C48's direction,
       # not its name
       calmode(
           outfile='3C48.cl', direction='J2000 01h37m41.1s 33.155deg', band='Q',
           obsdate=55000, hosts=['http://some-host-that-works.nrao.edu']
       )   



.. _Development:

Development

 



.. _Details:


Parameter Details
   Detailed descriptions of each function parameter

.. _outfile:

| ``outfile (path='')`` - The name of the output component list to be written. Must be specified
|                         Default: none, must be specified
|                            Example: outfile='3c273.cl'

.. _source:

| ``source (string='')`` - The calibrator name. The case-insensitive names
|                        "3C48", "3C286", "3C138",
|                        and "3C147" are supported. Exactly one of source
|                        or direction must be specified.

.. _direction:

| ``direction (string='')`` - An alternative to source. It is the direction of the calibrator. The supported
|                        formats are of the form 'EPOCH LONGITUDE LATITUDE', eg
|                        
|                        'J2000 12:34:56 -12.34.56'.
|                        'J2000 19h53m50 40d06m00'
|                        'B1950 292.5deg -40.0deg'
|                        'ICRS 13:05:27.2780 -049.28.04.458'
|                        'GALACTIC 47.5rad -60.22rad'
|                        Only astronomical coordinate systems should be used; eg AZEL is right out. The web service
|                        will attempt to locate a known calibrator near this direction, where "near" is defined by
|                        the web service team. Exactly one of source or direction must be specified.

.. _band:

| ``band (string='')`` - A string representing the case-insensitive code of
|                        the band for which the data are required. For the VLA,
|                        supported codes are "P", "L", "S", "C", "X", "U", "K", "A", and "Q".

.. _obsdate:

| ``obsdate (variant='0')`` - The date for which to obtain the calibrator information. If numeric,
|                        is assumed to be an MJD. If a string, is assumed to be a date and must
|                        be of the form "YYYY-MM-DD".

.. _refdate:

| ``refdate (variant='0')`` - The reference date after which new database entries will be ignored. If numeric,
|                        is assumed to be an MJD. If a string, is assumed to be a date and must
|                        be of the form "YYYY-MM-DD". Used to support
|                        historical reproducibility. A non-positive value will result in this parameter being ignored,
|                        and the most recent entry will be used (which may be later than obsdate).

.. _hosts:

| ``hosts (stringVec=['http://something.nrao.edu'])`` - List of hostnames to use when querying the web service. They will be queried in
|                        order until a successful response is received.


    """


    if not outfile.strip():
        raise ValueError('outfile must be specified')
    if not (source.strip() or direction.strip()):
        raise ValueError('Exactly one of source or direction must be specified')
    if source and direction:
        raise ValueError('Both source and direction may not be simultaneously specified')
    if source and source.upper() not in ("3C48", "3C286", "3C138", "3C147"):
        raise ValueError(f'Unsupported calibrator {source}')
    if direction:
        dirstr = direction.split(' ')
        if not (len(dirstr) == 3 and measures().direction(dirstr[0], dirstr[1], dirstr[2])):
            raise ValueError(f'Illegal direction specification {direction}')
    src_or_dir = source if source else direction
    if not band:
        raise ValueError('band must be specified')
    if band.upper() not in ["P", "L", "S", "C", "X", "U", "K", "A", "Q"]:
        raise ValueError(f'band {band} not supported')
    print('*****', obsdate)
    if isinstance(obsdate, numbers.Number):
    	if obsdate > 0 and obsdate < 44239:
            raise ValueError('If specified as a number, obsdate must be <= 0 or >= 44239')
    elif isinstance(obsdate, str):
        pattern = '^\d{4}-\d{2}-\d{2}$'
        if not re.match(pattern, obsdate):
            raise ValueError(
                'If specified as a string, obsdate must be of the form YYYY-MM-DD'
            )
        else:
            obsdate = int(obsdate[0][:obsdate[0].index('/')])
    else:
        raise ValueError(
            'obsdate must either be a number or a string of the form YYYY-MM-DD'
        )
    if isinstance(refdate, numbers.Number):
        if refdate > 0 and refdate < 44239:
            raise ValueError('if number, refdate must be <= 0 or >= 44239')
    elif isinstance(refdate, str):
        pattern = '^\d{4}-\d{2}-\d{2}$'
        if not re.match(pattern, refdate):
            raise ValueError(
                'refdate must either be a number or a string of the form YYYY-MM-DD'
            )
        else:
            refdate = int(refdate[0][:refdate[0].index('/')])
    else:
        raise ValueError(
            'refdate must either be a number or a string of the form YYYY-MM-DD'
        )
    if not hosts:
        raise ValueError('hosts must be specified')
    wsid = 'type=setjy'
    wsid += f'&source={quote(source)}' if source else f'&position={quote(direction)}'
    wsid += f'&band={quote(band)}'
    wsid += f'&obsdate={int(obsdate)}'
    if refdate > 0:
        wsid += f'&refdate={int(refdate)}'
    components = None
    for h in hosts:
        if not __is_valid_url_host(h):
            raise ValueError(f'{h} is not a valid host expressed as a URL')
        url = f'{h}?{wsid}'
        casalog.post(f'Trying {url} ...', 'NORMAL')
        try:
            components = __query(url)
        except HTTPError as e:
            casalog.post(f'Caught HTTPError: {str(e)}', 'WARN')
        except URLError as e:
            casalog.post(f'Caught URLError: {str(e)}', 'WARN')
        except Exception as e:
            casalog.post(f'Caught Exception when trying to connect: {str(e)}', 'WARN')
        if components:
            break
    if not components:
        raise RuntimeError('All URLs failed to return a component list')
    cl = componentlist()
    cl.fromrecord(components)
    cl.rename(outfile)
    web_service = {}
    if source:
        web_service['source'] = source
    if direction:
        web_service['direction'] = direction
    if obsdate:
        web_service['obsdate'] = obsdate
    if refdate:
        web_service['refdate'] = refdate
    web_service['band'] = band
    web_service['hosts'] = hosts
    qa = quanta()
    web_service['run_mjd'] = int(
        qa.time(
            f'{datetime.today().strftime("%Y-%m-%d")} 00:00:00', form='mjd'
        )[0][:5]
    )
    web_service['run_date'] = datetime.today().strftime('%Y-%m-%d')
    web_service['url'] = url
    web_service['response'] = components
    cl.putkeyword('web_service', web_service)
    casalog.post(f'component list {outfile} has been written', 'NORMAL')
    cl.done()
    
